SELECT
    PROD.SORDER.CPY_0,
    PROD.SORDER.SOHNUM_0,
    PROD.SORDERQ.SOPLIN_0,
    10 AS ID_STATO_ORD,
    PROD.SORDER.SOHTEX1_0
FROM
    PROD.SORDER
    INNER JOIN PROD.SORDERQ ON (PROD.SORDER.SOHNUM_0 = PROD.SORDERQ.SOHNUM_0)
    AND (PROD.SORDER.CPY_0 = PROD.SORDERQ.CPY_0)
WHERE
    (
        ((PROD.SORDER.CPY_0) = "DBELE")
        AND ((PROD.SORDERQ.SOQSTA_0) <> 3)
    )