SELECT
    PROD.SORDER.YCUSORDREF_0 AS RIF_INT,
    PROD.SORDER.YCOMMERCIALE_0 AS COMMERCIALE,
    PROD.SORDER.CPY_0,
    PROD.SORDER.SOHNUM_0 AS N_ORDINE,
    PROD.SORDER.SOHTYP_0 AS TIPO_ORDINE,
    PROD.SORDERQ.SOPLIN_0 AS N_RIGA,
    PROD.SORDER.CUSORDREF_0 AS RIF_CLI,
    PROD.SORDERQ.ITMREF_0 AS ARTICOLO,
    PROD.ITMMASTER.YITMOLD_0 AS OLD_CODE,
    PROD.SORDERP.ITMDES_0 AS DES_ARTICOLO,
    PROD.SORDERQ.QTY_0 AS QTA_ORD,
    PROD.SORDERQ.DLVQTY_0 AS QTA_CONS,
    PROD.SORDERQ.INVQTY_0 AS QTA_FATT,
    PROD.SORDERQ.SOQSTA_0 AS STATO_RIGA,
    PROD.SORDERQ.DEMSTA_0,
    PROD.SORDER.BPCORD_0 AS CD_CLIENTE,
    PROD.BPARTNER.BPRNAM_0 AS DES_CLIENTE,
    PROD.SORDER.ORDDAT_0 AS DATA_ORD,
    PROD.SORDERQ.DEMDLVDAT_0 AS DATA_RICH_CONS,
    PROD.SORDERQ.EXTDLVDAT_0 AS DATA_CONS_PREV,
    PROD.SORDERQ.SHIDAT_0 AS DATA_SPED
FROM
    (
        (
            (
                PROD.SORDER
                INNER JOIN PROD.SORDERQ ON (PROD.SORDER.SOHNUM_0 = PROD.SORDERQ.SOHNUM_0)
                AND (PROD.SORDER.CPY_0 = PROD.SORDERQ.CPY_0)
            )
            INNER JOIN PROD.BPARTNER ON PROD.SORDER.BPCORD_0 = PROD.BPARTNER.BPRNUM_0
        )
        INNER JOIN PROD.SORDERP ON (PROD.SORDERQ.SOHNUM_0 = PROD.SORDERP.SOHNUM_0)
        AND (PROD.SORDERQ.SOPLIN_0 = PROD.SORDERP.SOPLIN_0)
        AND (PROD.SORDERQ.CPY_0 = PROD.SORDERP.CPY_0)
    )
    INNER JOIN PROD.ITMMASTER ON PROD.SORDERQ.ITMREF_0 = PROD.ITMMASTER.ITMREF_0
WHERE
    (
        ((PROD.SORDER.CPY_0) = 'DBELE')
        AND ((PROD.SORDERQ.SOQSTA_0) <> 3)
        AND ((PROD.SORDERQ.DEMSTA_0) = 1)
    )