# Generated by Django 5.2.3 on 2025-06-30 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utenti",
            name="user",
        ),
    ]
