# Generated by Django 5.2.3 on 2025-07-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0002_remove_utenti_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profili",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("ruolo", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profili_stati",
            name="ruolo",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("Amministratore", "Amministratore"),
                    ("Pianificazione", "Pianificazione"),
                    ("Logistica", "Logistica"),
                    ("Responsabile Produzione", "Responsabile Produzione"),
                    ("Commerciale", "Commerciale"),
                    ("Produzione", "Produzione"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produzione.profili",
            ),
        ),
        migrations.AlterField(
            model_name="utenti",
            name="ruolo",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    (1, "Amministratore"),
                    (2, "Pianificazione"),
                    (3, "Logistica"),
                    (4, "Responsabile Produzione"),
                    (5, "Commerciale"),
                    (6, "Produzione"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produzione.profili",
            ),
        ),
    ]
