# Generated by Django 5.2.3 on 2025-07-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0003_profili_alter_profili_stati_ruolo_alter_utenti_ruolo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profili_stati",
            name="ruolo",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    (1, "Amministratore"),
                    (2, "Pianificazione"),
                    (3, "Logistica"),
                    (4, "Responsabile Produzione"),
                    (5, "Commerciale"),
                    (6, "Produzione"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produzione.profili",
            ),
        ),
    ]
