# Generated by Django 5.2.3 on 2025-07-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0004_alter_profili_stati_ruolo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profili_stati",
            name="ruolo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produzione.profili",
            ),
        ),
        migrations.AlterField(
            model_name="utenti",
            name="ruolo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produzione.profili",
            ),
        ),
    ]
