# Generated by Django 5.2.3 on 2025-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0005_alter_profili_stati_ruolo_alter_utenti_ruolo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utenti",
            name="ruolo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
