# Generated by Django 5.2.3 on 2025-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produzione", "0008_alter_profili_stati_ruolo_alter_utenti_ruolo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avanzamento_ordini",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="avanzamento_ordini",
            name="note_prod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
