# Generated by Django 5.2.3 on 2025-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0009_alter_avanzamento_ordini_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenti',
            name='is_operatore',
            field=models.BooleanField(null=True),
        ),
    ]
