# Generated by Django 5.2.3 on 2025-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0010_utenti_is_operatore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avanzamento_ordini',
            name='note_prod',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
