# Generated by Django 4.2.23 on 2025-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0011_alter_avanzamento_ordini_note_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avanzamento_ordini',
            name='all_ord',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
