# Generated by Django 5.2.4 on 2025-08-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0012_alter_avanzamento_ordini_all_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profili_stati',
            name='tipo_uso',
        ),
    ]
