# Generated by Django 5.2.4 on 2025-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0013_remove_profili_stati_tipo_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profili_stati',
            name='tipo_uso',
            field=models.CharField(choices=[('V', 'Visione'), ('S', 'Scrittura')], default='V', max_length=1),
        ),
    ]
