# Generated by Django 5.2.4 on 2025-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0014_profili_stati_tipo_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='avanzamento_ordini',
            name='data_consegna_effettiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
